//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AXMbsDevEntities : DbContext
    {
        public AXMbsDevEntities()
            : base("name=AXMbsDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CUSTINVOICEJOUR> CUSTINVOICEJOUR { get; set; }
        public DbSet<CUSTINVOICETRANS> CUSTINVOICETRANS { get; set; }
        public DbSet<CUSTTABLE> CUSTTABLE { get; set; }
        public DbSet<DATAAREA> DATAAREA { get; set; }
        public DbSet<MBSBDSALESREPTABLE> MBSBDSALESREPTABLE { get; set; }
        public DbSet<MBSWBWEBUSERCONTACT> MBSWBWEBUSERCONTACT { get; set; }
    }
}
