//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTINVOICEJOUR
    {
        public string SALESID { get; set; }
        public string ORDERACCOUNT { get; set; }
        public System.DateTime INVOICEDATE { get; set; }
        public decimal SALESBALANCE { get; set; }
        public decimal INVOICEAMOUNT { get; set; }
        public string INVOICEID { get; set; }
        public decimal SUMTAX { get; set; }
        public string MBSPRIMARYSALESREP { get; set; }
        public string DATAAREAID { get; set; }
        public long RECID { get; set; }
    }
}
