//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTINVOICETRANS
    {
        public string INVOICEID { get; set; }
        public System.DateTime INVOICEDATE { get; set; }
        public string INVENTTRANSID { get; set; }
        public string ITEMID { get; set; }
        public string NAME { get; set; }
        public decimal QTY { get; set; }
        public decimal SALESPRICE { get; set; }
        public decimal LINEAMOUNT { get; set; }
        public string DATAAREAID { get; set; }
        public long RECID { get; set; }
    }
}
