//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBSWBWEBUSERCONTACT
    {
        public string ACCOUNTNUM { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string WEBLOGON { get; set; }
        public string WEBPASSWORD { get; set; }
        public string CONTACTPERSONID { get; set; }
        public string SALESREPID { get; set; }
        public string DATAAREAID { get; set; }
        public long RECID { get; set; }
    }
}
